baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Example Graysx Site'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
address = "123 Arch B1W, GNU/Linux"
email = "hello@graysx.com"
phone = "123456"

# Socials

twitter = "#"
facebook = "#"
github = "https://github.com/akatiggerx04/graysx-hugo"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04